const T = (items: string[]) => Object.freeze(items);

/** Gatilhos compartilhados reutilizáveis. */
export const SHARED = {
  today: T([
    "hoje",
    "dia de hoje",
    "neste dia",
    "neste momento",
    "agora",
    "do dia",
    "diario",
    "diária",
  ]),
  yesterday: T(["ontem", "dia anterior", "dia passado", "de ontem"]),
  help: T([
    "como ",
    "como fazer",
    "como criar",
    "como cadastrar",
    "como agendar",
    "como faturar",
    "onde ",
    "onde fica",
    "onde encontro",
    "me ajuda",
    "me ajude",
    "preciso de ajuda",
    "ajuda",
    "tutorial",
    "passo a passo",
    "o que fazer",
    "como funciona",
    "explica",
    "explicar",
    "manual",
    "documentacao",
    "documentação",
  ]),
} as const;

export type MockIntentDef = {
  tool: string;
  roles?: readonly string[];
  triggers: readonly string[];
  priority?: number;
  special?: "create_user" | "create_patient" | "create_appointment" | "book_appointment";
};

export const MOCK_INTENTS: readonly MockIntentDef[] = [
  {
    tool: "count_appointments",
    roles: ["INTERNO"],
    priority: 10,
    triggers: T([
      "agendamento",
      "agendamentos",
      "agenda do dia",
      "agenda de hoje",
      "agenda de ontem",
      "consulta",
      "consultas",
      "atendimento",
      "atendimentos",
      "sessao",
      "sessão",
      "sessoes",
      "sessões",
      "aula",
      "aulas",
      "horario marcado",
      "horário marcado",
      "compromisso",
      "compromissos",
      "quantos agendamentos",
      "quantas consultas",
      "quantos atendimentos",
      "numero de agendamentos",
      "número de agendamentos",
      "qtd agendamentos",
      "total de agendamentos",
      "total de consultas",
      "marcacoes",
      "marcações",
      "calendario",
      "calendário",
      "o que tem na agenda",
      "o que temos hoje na agenda",
      "lotacao do dia",
      "lotação do dia",
      "movimento da agenda",
      "agenda lotada",
      "pauta do dia",
      "escala do dia",
      "agenda de hoje",
      "agenda de ontem",
      "consultas de hoje",
      "consultas de ontem",
      "agendamentos de hoje",
      "agendamentos de ontem",
    ]),
  },
  {
    tool: "get_revenue_summary",
    roles: ["INTERNO"],
    priority: 10,
    triggers: T([
      "receita",
      "faturamento",
      "faturado",
      "faturada",
      "faturar",
      "faturei",
      "faturou",
      "fatura",
      "faturas",
      "quanto faturamos",
      "quanto faturou",
      "quanto entrou",
      "quanto ganhamos",
      "quanto arrecadamos",
      "entrada financeira",
      "volume faturado",
      "total faturado",
      "total de receita",
      "resumo financeiro",
      "resumo de faturamento",
      "panorama financeiro",
      "financeiro do dia",
      "financeiro de ontem",
      "resultado financeiro",
      "billing",
      "pay per use",
      "pay-per-use",
      "procedimentos faturados",
      "valor faturado",
      "quanto foi faturado",
      "fechamento do dia",
      "fechamento financeiro",
      "caixa do dia",
      "movimentacao financeira",
      "movimentação financeira",
      "receita de hoje",
      "receita de ontem",
      "faturamento de hoje",
      "faturamento de ontem",
    ]),
  },
  {
    tool: "list_debtors",
    roles: ["INTERNO"],
    priority: 10,
    triggers: T([
      "devedor",
      "devedores",
      "devendo",
      "quem deve",
      "quem esta devendo",
      "quem está devendo",
      "inadimplente",
      "inadimplentes",
      "inadimplencia",
      "inadimplência",
      "pendencia",
      "pendência",
      "pendencias",
      "pendências",
      "cobranca",
      "cobrança",
      "cobrancas",
      "cobranças",
      "a receber",
      "em aberto",
      "nao pagou",
      "não pagou",
      "nao pagaram",
      "não pagaram",
      "falta pagar",
      "falta pagamento",
      "pagamento pendente",
      "pagamentos pendentes",
      "divida",
      "dívida",
      "dividas",
      "dívidas",
      "debito",
      "débito",
      "debitos",
      "débitos",
      "saldo devedor",
      "clientes devedores",
      "beneficiarios devedores",
      "beneficiários devedores",
      "quem nao quitou",
      "quem não quitou",
      "lista de devedores",
      "relatorio de inadimplencia",
      "relatório de inadimplência",
    ]),
  },
  {
    tool: "get_dashboard_kpis",
    roles: ["INTERNO"],
    priority: 8,
    triggers: T([
      "dashboard",
      "painel",
      "indicador",
      "indicadores",
      "kpi",
      "kpis",
      "metrica",
      "métrica",
      "metricas",
      "métricas",
      "resumo",
      "resumo geral",
      "visao geral",
      "visão geral",
      "panorama",
      "panorama geral",
      "situacao geral",
      "situação geral",
      "como estamos",
      "como esta a operacao",
      "como está a operação",
      "status da operacao",
      "status da operação",
      "numeros gerais",
      "números gerais",
      "estatistica",
      "estatística",
      "estatisticas",
      "estatísticas",
      "executivo",
      "dashboard executivo",
      "big numbers",
      "totais gerais",
      "overview",
      "resumo executivo",
      "saude da operacao",
      "saúde da operação",
    ]),
  },
  {
    tool: "list_users",
    roles: ["INTERNO"],
    priority: 9,
    triggers: T([
      "listar usuarios",
      "listar usuários",
      "lista de usuarios",
      "lista de usuários",
      "usuarios cadastrados",
      "usuários cadastrados",
      "quem tem acesso",
      "contas do sistema",
      "contas cadastradas",
      "equipe",
      "equipe cadastrada",
      "prestadores cadastrados",
      "medicos cadastrados",
      "médicos cadastrados",
      "internos cadastrados",
      "usuarios do tenant",
      "usuários do tenant",
      "relacao de usuarios",
      "relação de usuários",
      "mostrar usuarios",
      "mostrar usuários",
      "ver usuarios",
      "ver usuários",
      "usuarios ativos",
      "usuários ativos",
    ]),
  },
  {
    tool: "search_patients",
    roles: ["INTERNO"],
    priority: 11,
    triggers: T([
      "buscar paciente",
      "buscar beneficiario",
      "buscar beneficiário",
      "procurar paciente",
      "procurar beneficiario",
      "procurar beneficiário",
      "encontrar paciente",
      "pesquisar paciente",
      "localizar paciente",
      "achar paciente",
      "cpf",
      "buscar por cpf",
      "procurar por cpf",
      "buscar por nome",
      "procurar por nome",
      "pesquisar por nome",
      "qual o cadastro",
      "dados do paciente",
      "dados do beneficiario",
      "dados do beneficiário",
      "ficha do paciente",
      "cadastro de",
    ]),
  },
  {
    tool: "explain_capability",
    roles: ["INTERNO"],
    priority: 12,
    triggers: SHARED.help,
  },
  {
    tool: "draft_create_user",
    roles: ["INTERNO"],
    special: "create_user",
    priority: 20,
    triggers: T([
      "criar usuario",
      "criar usuário",
      "cadastrar usuario",
      "cadastrar usuário",
      "novo usuario",
      "novo usuário",
      "adicionar usuario",
      "adicionar usuário",
      "registrar usuario",
      "registrar usuário",
      "incluir usuario",
      "incluir usuário",
      "criar conta",
      "cadastrar conta",
      "nova conta",
      "criar login",
      "cadastrar login",
      "novo prestador",
      "cadastrar prestador",
      "criar prestador",
      "novo interno",
      "cadastrar interno",
      "criar acesso",
      "dar acesso",
      "liberar acesso",
    ]),
  },
  {
    tool: "draft_create_patient",
    roles: ["INTERNO"],
    special: "create_patient",
    priority: 20,
    triggers: T([
      "criar paciente",
      "cadastrar paciente",
      "novo paciente",
      "criar beneficiario",
      "criar beneficiário",
      "cadastrar beneficiario",
      "cadastrar beneficiário",
      "novo beneficiario",
      "novo beneficiário",
      "adicionar paciente",
      "registrar paciente",
      "incluir paciente",
      "novo cadastro",
      "cadastro novo",
      "criar pet",
      "cadastrar pet",
      "novo cliente",
      "cadastrar cliente",
      "novo aluno",
      "cadastrar aluno",
      "novo tutor",
      "cadastrar tutor",
      "walk in",
      "walk-in",
    ]),
  },
  {
    tool: "draft_create_appointment",
    roles: ["INTERNO"],
    special: "create_appointment",
    priority: 20,
    triggers: T([
      "agendar",
      "marcar consulta",
      "marcar uma consulta",
      "preciso marcar",
      "quero marcar uma consulta",
      "marcar atendimento",
      "criar agendamento",
      "novo agendamento",
      "incluir agendamento",
      "reservar horario",
      "reservar horário",
      "marcar horario",
      "marcar horário",
      "encaixe",
      "encaixar",
      "agendar consulta",
      "agendar atendimento",
      "agendar sessao",
      "agendar sessão",
      "colocar na agenda",
      "inserir na agenda",
      "nova consulta",
      "novo compromisso",
    ]),
  },
  {
    tool: "get_prestador_dashboard",
    roles: ["PRESTADOR"],
    priority: 7,
    triggers: T([
      "dashboard",
      "painel",
      "resumo",
      "resumo do dia",
      "minha operacao",
      "minha operação",
      "como esta meu dia",
      "como está meu dia",
      "visao geral",
      "visão geral",
      "indicadores",
      "meus numeros",
      "meus números",
      "status do dia",
      "fila de hoje",
      "minha fila",
    ]),
  },
  {
    tool: "list_my_appointments",
    roles: ["PRESTADOR"],
    priority: 10,
    triggers: T([
      "minha agenda",
      "agenda de hoje",
      "agenda do dia",
      "meus agendamentos",
      "minhas consultas",
      "meus atendimentos",
      "consultas de hoje",
      "atendimentos de hoje",
      "o que tenho hoje",
      "compromissos de hoje",
      "horarios de hoje",
      "horários de hoje",
      "pauta de hoje",
      "escala de hoje",
      "proximos pacientes",
      "próximos pacientes",
      "quem atendo hoje",
      "agenda",
      "consulta",
      "atendimento",
      "agenda de hoje",
      "agenda de ontem",
    ]),
  },
  {
    tool: "list_my_patients",
    roles: ["PRESTADOR"],
    priority: 9,
    triggers: T([
      "meus pacientes",
      "minhas pacientes",
      "lista de pacientes",
      "pacientes atendidos",
      "carteira de pacientes",
      "meus clientes",
      "meus alunos",
      "meus pets",
      "paciente",
      "cliente",
      "aluno",
      "pet",
      "buscar paciente",
      "procurar paciente",
    ]),
  },
  {
    tool: "get_extrato_summary",
    roles: ["PRESTADOR"],
    priority: 10,
    triggers: T([
      "extrato",
      "meu extrato",
      "extrato do mes",
      "extrato do mês",
      "quanto recebi",
      "quanto ganhei",
      "minha receita",
      "receita",
      "ganhos",
      "producao",
      "produção",
      "procedimentos realizados",
      "honorarios",
      "honorários",
      "repasse",
      "financeiro",
      "resumo financeiro",
      "faturamento",
      "extrato de hoje",
      "extrato de ontem",
    ]),
  },
  {
    tool: "get_pj_overview",
    roles: ["PJ"],
    priority: 7,
    triggers: T([
      "resumo",
      "resumo da empresa",
      "visao geral",
      "visão geral",
      "dashboard",
      "painel",
      "overview",
      "como esta a empresa",
      "como está a empresa",
      "situacao da empresa",
      "situação da empresa",
      "status da empresa",
      "numeros da empresa",
      "números da empresa",
      "panorama",
      "contrato",
      "minha empresa",
    ]),
  },
  {
    tool: "list_company_beneficiaries",
    roles: ["PJ"],
    priority: 9,
    triggers: T([
      "beneficiarios",
      "beneficiários",
      "colaboradores",
      "funcionarios",
      "funcionários",
      "empregados",
      "equipe",
      "lista de beneficiarios",
      "lista de beneficiários",
      "quem esta coberto",
      "quem está coberto",
      "vidas",
      "vidas ativas",
      "carteirinha",
      "dependentes",
      "buscar colaborador",
      "procurar beneficiario",
    ]),
  },
  {
    tool: "get_open_invoices",
    roles: ["PJ"],
    priority: 10,
    triggers: T([
      "fatura",
      "faturas",
      "faturas em aberto",
      "faturas abertas",
      "boletos",
      "boletos em aberto",
      "pagamentos pendentes",
      "o que devemos",
      "quanto devemos",
      "divida",
      "dívida",
      "inadimplencia",
      "inadimplência",
      "cobranca",
      "cobrança",
      "devedor",
      "em aberto",
      "a pagar",
      "contas a pagar",
    ]),
  },
  {
    tool: "get_my_overview",
    roles: ["BENEFICIARIO"],
    priority: 7,
    triggers: T([
      "meu resumo",
      "resumo",
      "minha conta",
      "minha situacao",
      "minha situação",
      "como estou",
      "meus dados",
      "overview",
      "painel",
      "dashboard",
      "o que tenho pendente",
      "minha saude",
      "minha saúde",
    ]),
  },
  {
    tool: "list_my_appointments",
    roles: ["BENEFICIARIO"],
    priority: 10,
    triggers: T([
      "meus agendamentos",
      "minhas consultas",
      "minha agenda",
      "proximos agendamentos",
      "próximos agendamentos",
      "proxima consulta",
      "próxima consulta",
      "quando e minha consulta",
      "quando é minha consulta",
      "agenda",
      "consulta",
      "compromissos",
      "horarios marcados",
      "horários marcados",
      "o que tenho agendado",
    ]),
  },
  {
    tool: "list_my_invoices",
    roles: ["BENEFICIARIO"],
    priority: 10,
    triggers: T([
      "minhas faturas",
      "meus boletos",
      "faturas",
      "boletos",
      "o que devo",
      "quanto devo",
      "pagamentos",
      "contas",
      "contas a pagar",
      "pagar",
      "pix",
      "cobranca",
      "cobrança",
      "segunda via",
    ]),
  },
  {
    tool: "list_available_slots",
    roles: ["BENEFICIARIO"],
    priority: 11,
    triggers: T([
      "horarios disponiveis",
      "horários disponíveis",
      "vagas",
      "slots",
      "horarios livres",
      "horários livres",
      "quando posso agendar",
      "tem horario",
      "tem horário",
      "disponibilidade",
      "agendar",
      "marcar consulta",
      "marcar horario",
      "marcar horário",
      "quero agendar",
      "preciso agendar",
      "horarios disponiveis hoje",
      "horários disponíveis hoje",
    ]),
  },
  {
    tool: "draft_book_appointment",
    roles: ["BENEFICIARIO"],
    special: "book_appointment",
    priority: 15,
    triggers: T([
      "confirmar agendamento",
      "reservar horario",
      "reservar horário",
      "quero marcar",
      "marcar para",
    ]),
  },
] as const;

export function countMockTriggers(): number {
  const set = new Set<string>();
  for (const intent of MOCK_INTENTS) {
    for (const t of intent.triggers) {
      set.add(t.toLowerCase().normalize("NFD").replace(/\p{M}/gu, ""));
    }
  }
  return set.size;
}
