import type { CompanyStatus } from "../../src/lib/company-crm";

/**
 * Massa de 50 empresas PJ mapeadas a casos reais de mercado (benefício corporativo,
 * saúde ocupacional, telemedicina, Pay Per Use). Setores e cenários inspirados em
 * contratos típicos de operadoras e clínicas B2B no Brasil.
 */
export type SeedCompany = {
  /** Índice estável para CNPJ/CPF determinísticos */
  index: number;
  name: string;
  cnpj: string;
  status: CompanyStatus;
  sector: string;
  /** Caso de uso / motivo comercial (documentação do seed) */
  useCase: string;
  /** Beneficiários a gerar (0 para leads/propostas) */
  beneficiaryCount: number;
  /** Desconto corporativo em consulta clínica (multiplier), se houver */
  clinicalDiscount?: number;
  /** E-mail fixo do usuário PJ (apenas empresas demo principais) */
  pjEmail?: string;
};

const C = (index: number, cnpj: string) => cnpj;

export const SEED_COMPANIES: SeedCompany[] = [
  // —— ATIVOS (24) — casos reais de contrato vigente ——
  {
    index: 1,
    name: "TechCorp Benefícios LTDA",
    cnpj: C(1, "98.765.432/0001-10"),
    status: "ATIVO",
    sector: "Tecnologia",
    useCase: "Startup scale-up — telemedicina 24h e consultas Pay Per Use para 120 devs",
    beneficiaryCount: 12,
    clinicalDiscount: 0.85,
    pjEmail: "rh@techcorp.com",
  },
  {
    index: 2,
    name: "Banco Horizonte SA",
    cnpj: C(2, "10.111.222/0001-33"),
    status: "ATIVO",
    sector: "Financeiro",
    useCase: "Instituição financeira — programa executivo + check-up anual obrigatório",
    beneficiaryCount: 15,
    clinicalDiscount: 0.9,
  },
  {
    index: 3,
    name: "Rede Varejo Brasil LTDA",
    cnpj: C(3, "10.222.333/0001-44"),
    status: "ATIVO",
    sector: "Varejo",
    useCase: "Rede de lojas — atendimento em horário estendido para colaboradores de loja",
    beneficiaryCount: 10,
    clinicalDiscount: 0.88,
  },
  {
    index: 4,
    name: "Metalúrgica São Paulo Indústria",
    cnpj: C(4, "10.333.444/0001-55"),
    status: "ATIVO",
    sector: "Indústria",
    useCase: "PCMSO fabril — exames admissionais e periódicos com faturamento por uso",
    beneficiaryCount: 8,
    clinicalDiscount: 0.82,
  },
  {
    index: 5,
    name: "LogTrans Rodoviário SA",
    cnpj: C(5, "10.444.555/0001-66"),
    status: "ATIVO",
    sector: "Logística",
    useCase: "Transportadora — saúde do motorista (ASO, ECG, consultas em rota)",
    beneficiaryCount: 6,
  },
  {
    index: 6,
    name: "Construtora Alfa Engenharia",
    cnpj: C(6, "10.555.666/0001-77"),
    status: "ATIVO",
    sector: "Construção Civil",
    useCase: "Obra civil — medicina do trabalho e atendimento em canteiro",
    beneficiaryCount: 9,
    clinicalDiscount: 0.85,
  },
  {
    index: 7,
    name: "AgroCampos Cooperativa",
    cnpj: C(7, "10.666.777/0001-88"),
    status: "ATIVO",
    sector: "Agronegócio",
    useCase: "Cooperativa rural — telemedicina para interior e exames laboratoriais",
    beneficiaryCount: 7,
  },
  {
    index: 8,
    name: "EducaMais Instituto",
    cnpj: C(8, "10.777.888/0001-99"),
    status: "ATIVO",
    sector: "Educação",
    useCase: "Rede de escolas — plano saúde para professores e funcionários administrativos",
    beneficiaryCount: 11,
    clinicalDiscount: 0.87,
  },
  {
    index: 9,
    name: "FarmaVida Distribuidora",
    cnpj: C(9, "10.888.999/0001-00"),
    status: "ATIVO",
    sector: "Saúde",
    useCase: "Distribuidora farmacêutica — benefício corporativo para equipe comercial",
    beneficiaryCount: 5,
  },
  {
    index: 10,
    name: "ConsultPro Serviços LTDA",
    cnpj: C(10, "10.999.000/0001-11"),
    status: "ATIVO",
    sector: "Serviços",
    useCase: "Consultoria — modelo flex Pay Per Use para PJ com equipe remota",
    beneficiaryCount: 4,
    clinicalDiscount: 0.92,
  },
  {
    index: 11,
    name: "Hotelaria Praia Azul",
    cnpj: C(11, "11.000.111/0001-22"),
    status: "ATIVO",
    sector: "Hospitalidade",
    useCase: "Rede hoteleira — atendimento para equipe de temporada e housekeeping",
    beneficiaryCount: 8,
  },
  {
    index: 12,
    name: "Indústria Química Delta",
    cnpj: C(12, "11.111.222/0001-33"),
    status: "ATIVO",
    sector: "Química",
    useCase: "Indústria química — exames toxicológicos e consultas ocupacionais",
    beneficiaryCount: 6,
    clinicalDiscount: 0.8,
  },
  {
    index: 13,
    name: "E-commerce Rápido Entrega",
    cnpj: C(13, "11.222.333/0001-44"),
    status: "ATIVO",
    sector: "E-commerce",
    useCase: "Fulfillment — saúde para operadores de CD e entregadores parceiros",
    beneficiaryCount: 10,
  },
  {
    index: 14,
    name: "Seguros União Nacional",
    cnpj: C(14, "11.333.444/0001-55"),
    status: "ATIVO",
    sector: "Seguros",
    useCase: "Seguradora — benefício interno + integração webhook para ERP",
    beneficiaryCount: 7,
    clinicalDiscount: 0.9,
  },
  {
    index: 15,
    name: "TecnoSoft Desenvolvimento",
    cnpj: C(15, "11.444.555/0001-66"),
    status: "ATIVO",
    sector: "Tecnologia",
    useCase: "Software house — telemedicina e psicologia corporativa (recorrência)",
    beneficiaryCount: 5,
    clinicalDiscount: 0.88,
  },
  {
    index: 16,
    name: "Alimentos Bom Sabor SA",
    cnpj: C(16, "11.555.666/0001-77"),
    status: "ATIVO",
    sector: "Alimentos",
    useCase: "Indústria alimentícia — ASO e exames periódicos NR-7",
    beneficiaryCount: 9,
  },
  {
    index: 17,
    name: "Energia Solar Verde LTDA",
    cnpj: C(17, "11.666.777/0001-88"),
    status: "ATIVO",
    sector: "Energia",
    useCase: "Instaladora solar — equipes de campo com teleatendimento",
    beneficiaryCount: 4,
  },
  {
    index: 18,
    name: "Call Center Atende Mais",
    cnpj: C(18, "11.777.888/0001-99"),
    status: "ATIVO",
    sector: "BPO",
    useCase: "BPO — saúde mental e consultas rápidas para operadores de call",
    beneficiaryCount: 12,
    clinicalDiscount: 0.86,
  },
  {
    index: 19,
    name: "Laboratório Diagnóstico Norte",
    cnpj: C(19, "11.888.999/0001-00"),
    status: "ATIVO",
    sector: "Saúde",
    useCase: "Lab parceiro — benefício cruzado para colaboradores internos",
    beneficiaryCount: 3,
  },
  {
    index: 20,
    name: "Moda & Estilo Confecções",
    cnpj: C(20, "11.999.000/0001-11"),
    status: "ATIVO",
    sector: "Têxtil",
    useCase: "Confecção — medicina do trabalho para costureiras e produção",
    beneficiaryCount: 7,
  },
  {
    index: 21,
    name: "Mineração Vale do Oeste",
    cnpj: C(21, "12.000.111/0001-22"),
    status: "ATIVO",
    sector: "Mineração",
    useCase: "Mineração — exames ocupacionais e cardiologia preventiva",
    beneficiaryCount: 8,
    clinicalDiscount: 0.83,
  },
  {
    index: 22,
    name: "Startup FinPay Pagamentos",
    cnpj: C(22, "12.111.222/0001-33"),
    status: "ATIVO",
    sector: "Fintech",
    useCase: "Fintech — benefício flexível Pay Per Use para time jovem",
    beneficiaryCount: 4,
    clinicalDiscount: 0.9,
  },
  {
    index: 23,
    name: "Hospital Rede Vida Administração",
    cnpj: C(23, "12.222.333/0001-44"),
    status: "ATIVO",
    sector: "Saúde",
    useCase: "Gestora hospitalar — saúde ocupacional dos próprios colaboradores",
    beneficiaryCount: 6,
  },
  {
    index: 24,
    name: "Petroquímica Litoral SA",
    cnpj: C(24, "12.333.444/0001-55"),
    status: "ATIVO",
    sector: "Petróleo e Gás",
    useCase: "Refinaria — PCMSO rigoroso com exames cardiológicos periódicos",
    beneficiaryCount: 10,
    clinicalDiscount: 0.81,
  },

  // —— INADIMPLENTES (3) ——
  {
    index: 25,
    name: "VelozCom Varejo",
    cnpj: C(25, "33.444.555/0001-66"),
    status: "INADIMPLENTE",
    sector: "Varejo",
    useCase: "Varejo — contrato ativo mas faturas em atraso há 60 dias",
    beneficiaryCount: 5,
  },
  {
    index: 26,
    name: "Importadora Global Trade",
    cnpj: C(26, "12.444.555/0001-66"),
    status: "INADIMPLENTE",
    sector: "Comércio Exterior",
    useCase: "Importadora — inadimplência após reestruturação societária",
    beneficiaryCount: 4,
  },
  {
    index: 27,
    name: "Gráfica Express Print",
    cnpj: C(27, "12.555.666/0001-77"),
    status: "INADIMPLENTE",
    sector: "Gráfica",
    useCase: "PME gráfica — atraso em PIX recorrente do plano corporativo",
    beneficiaryCount: 3,
  },

  // —— NEGOCIAÇÃO (7) ——
  {
    index: 28,
    name: "NovaLog Transportes SA",
    cnpj: C(28, "28.111.222/0001-33"),
    status: "NEGOCIACAO",
    sector: "Logística",
    useCase: "Transportadora — negociando tabela de exames para frota de 200 caminhões",
    beneficiaryCount: 0,
  },
  {
    index: 29,
    name: "Indústria Plásticos Modernos",
    cnpj: C(29, "12.666.777/0001-88"),
    status: "NEGOCIACAO",
    sector: "Indústria",
    useCase: "Indústria — proposta customizada de PCMSO + telemedicina",
    beneficiaryCount: 0,
  },
  {
    index: 30,
    name: "Rede Supermercados União",
    cnpj: C(30, "12.777.888/0001-99"),
    status: "NEGOCIACAO",
    sector: "Varejo",
    useCase: "Supermercadista — piloto em 3 lojas antes de rollout nacional",
    beneficiaryCount: 0,
  },
  {
    index: 31,
    name: "Clínica Odonto Sorriso Corp",
    cnpj: C(31, "12.888.999/0001-00"),
    status: "NEGOCIACAO",
    sector: "Saúde",
    useCase: "Rede odontológica — parceria white-label para pacientes corporativos",
    beneficiaryCount: 0,
  },
  {
    index: 32,
    name: "Tecnologia CloudNine",
    cnpj: C(32, "12.999.000/0001-11"),
    status: "NEGOCIACAO",
    sector: "Tecnologia",
    useCase: "SaaS B2B — benefício como perk para retenção de talentos",
    beneficiaryCount: 0,
  },
  {
    index: 33,
    name: "Cooperativa Médica Sul",
    cnpj: C(33, "13.000.111/0001-22"),
    status: "NEGOCIACAO",
    sector: "Saúde",
    useCase: "Cooperativa — integração TISS e faturamento por procedimento",
    beneficiaryCount: 0,
  },
  {
    index: 34,
    name: "Autopeças Rodas & Cia",
    cnpj: C(34, "13.111.222/0001-33"),
    status: "NEGOCIACAO",
    sector: "Automotivo",
    useCase: "Autopeças — negociação de desconto progressivo por volume",
    beneficiaryCount: 0,
  },

  // —— PROPOSTA (7) ——
  {
    index: 35,
    name: "PropostaMed Clínicas",
    cnpj: C(35, "55.666.777/0001-88"),
    status: "PROPOSTA",
    sector: "Saúde",
    useCase: "Rede de clínicas — proposta enviada aguardando aprovação do board",
    beneficiaryCount: 0,
  },
  {
    index: 36,
    name: "Universidade Futuro Aberto",
    cnpj: C(36, "13.222.333/0001-44"),
    status: "PROPOSTA",
    sector: "Educação",
    useCase: "Universidade — proposta de saúde para 800 docentes",
    beneficiaryCount: 0,
  },
  {
    index: 37,
    name: "Franquia Burger House",
    cnpj: C(37, "13.333.444/0001-55"),
    status: "PROPOSTA",
    sector: "Alimentação",
    useCase: "Franquia fast-food — proposta por unidade franqueada",
    beneficiaryCount: 0,
  },
  {
    index: 38,
    name: "Corretora Imóveis Prime",
    cnpj: C(38, "13.444.555/0001-66"),
    status: "PROPOSTA",
    sector: "Imobiliário",
    useCase: "Imobiliária — proposta para corretores autônomos vinculados",
    beneficiaryCount: 0,
  },
  {
    index: 39,
    name: "Startup HealthTech Inno",
    cnpj: C(39, "13.555.666/0001-77"),
    status: "PROPOSTA",
    sector: "HealthTech",
    useCase: "HealthTech — proposta piloto com webhook e API B2B",
    beneficiaryCount: 0,
  },
  {
    index: 40,
    name: "Cooperativa Crédito Rural",
    cnpj: C(40, "13.666.777/0001-88"),
    status: "PROPOSTA",
    sector: "Financeiro",
    useCase: "Cooperativa de crédito — proposta regional para associados",
    beneficiaryCount: 0,
  },
  {
    index: 41,
    name: "Indústria Têxtil Nordeste",
    cnpj: C(41, "13.777.888/0001-99"),
    status: "PROPOSTA",
    sector: "Têxtil",
    useCase: "Têxtil — proposta com foco em ergonomia e medicina preventiva",
    beneficiaryCount: 0,
  },

  // —— LEADS (8) ——
  {
    index: 42,
    name: "BetaStart Tecnologia",
    cnpj: C(42, "22.333.444/0001-55"),
    status: "LEAD",
    sector: "Tecnologia",
    useCase: "Startup early-stage — lead de indicação, 15 funcionários",
    beneficiaryCount: 0,
  },
  {
    index: 43,
    name: "Academia FitLife Rede",
    cnpj: C(43, "13.888.999/0001-00"),
    status: "LEAD",
    sector: "Fitness",
    useCase: "Rede de academias — lead de feira de RH corporativo",
    beneficiaryCount: 0,
  },
  {
    index: 44,
    name: "Distribuidora Bebidas Sul",
    cnpj: C(44, "13.999.000/0001-11"),
    status: "LEAD",
    sector: "Bebidas",
    useCase: "Distribuidora — lead inbound via landing page B2B",
    beneficiaryCount: 0,
  },
  {
    index: 45,
    name: "Escritório Advocacia Silva",
    cnpj: C(45, "14.000.111/0001-22"),
    status: "LEAD",
    sector: "Jurídico",
    useCase: "Escritório de advocacia — lead, 25 associados",
    beneficiaryCount: 0,
  },
  {
    index: 46,
    name: "Cooperativa Transporte Urbano",
    cnpj: C(46, "14.111.222/0001-33"),
    status: "LEAD",
    sector: "Transporte",
    useCase: "Cooperativa de ônibus — lead para saúde do motorista",
    beneficiaryCount: 0,
  },
  {
    index: 47,
    name: "Indústria Cerâmica Artesanal",
    cnpj: C(47, "14.222.333/0001-44"),
    status: "LEAD",
    sector: "Indústria",
    useCase: "Cerâmica — lead regional, interesse em exames ocupacionais",
    beneficiaryCount: 0,
  },
  {
    index: 48,
    name: "Marketing Digital Criativa",
    cnpj: C(48, "14.333.444/0001-55"),
    status: "LEAD",
    sector: "Marketing",
    useCase: "Agência digital — lead, time 100% remoto",
    beneficiaryCount: 0,
  },
  {
    index: 49,
    name: "Frigorífico Carnes Nobres",
    cnpj: C(49, "14.444.555/0001-66"),
    status: "LEAD",
    sector: "Alimentos",
    useCase: "Frigorífico — lead SIF, necessidade de PCMSO completo",
    beneficiaryCount: 0,
  },

  // —— CANCELADO (1) ——
  {
    index: 50,
    name: "OldCorp Encerrada",
    cnpj: C(50, "44.555.666/0001-77"),
    status: "CANCELADO",
    sector: "Serviços",
    useCase: "Empresa encerrada — contrato cancelado, histórico preservado",
    beneficiaryCount: 0,
  },
];

export const SEED_COMPANY_COUNT = SEED_COMPANIES.length;

/** Nomes brasileiros para geração de beneficiários */
export const FIRST_NAMES = [
  "João", "Maria", "Pedro", "Ana", "Carlos", "Fernanda", "Lucas", "Juliana",
  "Rafael", "Camila", "Bruno", "Patrícia", "Diego", "Larissa", "Gabriel",
  "Amanda", "Rodrigo", "Beatriz", "Felipe", "Mariana", "Gustavo", "Letícia",
  "Thiago", "Renata", "André", "Vanessa", "Marcos", "Priscila", "Ricardo",
  "Tatiane", "Eduardo", "Simone", "Paulo", "Adriana", "Henrique", "Cristina",
] as const;

export const LAST_NAMES = [
  "Silva", "Santos", "Oliveira", "Souza", "Pereira", "Costa", "Rodrigues",
  "Almeida", "Nascimento", "Lima", "Araújo", "Fernandes", "Carvalho", "Gomes",
  "Martins", "Rocha", "Ribeiro", "Alves", "Monteiro", "Mendes", "Barbosa",
  "Freitas", "Cardoso", "Teixeira", "Correia", "Moura", "Cavalcanti", "Dias",
] as const;
